version: 0.2

env:
  variables:
    AWS_REGION: us-east-1
    IMAGE_TAG: latest
    REPOSITORY_URI: 724772082770.dkr.ecr.us-east-1.amazonaws.com/deployment-685f7fa443b1bd7efbaffb73
    ECS_CLUSTER: my-cluster
    ECS_SERVICE: my-service

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Updating ECS service...
      - aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --force-new-deployment
      - echo Build completed on date